### ISSUE TITLE
Update `lockfileVersion : 1`  to 2

### ISSUE THREAD

**Issue by Saatvik-droid** [commclassroom/commclassroomBackend#23]
Version 2 is backwards compatible with v5 and v6. Whenever I run `npm i` with v7 it updates the `pacakge-lock.json` and causes a huge conflict.`

**Comment by YashKumarVerma** [comment]
NPM version had nothing to do with the error that we had on CI. It was because of an outdated lock file, which is resolved now. Closing.

**Comment by Saatvik-droid** [comment]
Alright, I've never faced this particular issue and couldn't find a lot on google except npm version conflicts.
