### ISSUE TITLE
Feature Request: Create new user and update user

### ISSUE THREAD

**Issue by Saatvik-droid** [commclassroom/commclassroomBackend#26]
I'd like to work on this if you could answer a couple of questions.

**Comment by Saatvik-droid** [comment]
1.I assume we will be adding a password to every user, is it to be done in this PR?
2.What does User details include?

**Comment by divyanshu-parihar** [comment]
@Saatvik-droid i think answer to you question is yes according to me atleast for the new user part and may be for the update user part too.

**Comment by divyanshu-parihar** [comment]
@Saatvik-droid , just want to know , have you started working on this ?

**Comment by Saatvik-droid** [comment]
@divyanshu-parihar No, I haven't as I want some clarity.

**Comment by YashKumarVerma** [comment]
> @divyanshu-parihar No, I haven't as I want some clarity.
> 
> If a lead can give me confirmation I'll start working on them.

will get back to you on this in 24 hours, have an exam scheduled right now. Till then you can leave the details of user schema, and implement the rest of it.

**Comment by Saatvik-droid** [comment]
@YashKumarVerma update?
