### ISSUE TITLE
[Feature]: User schema

### ISSUE THREAD

**Issue by Saatvik-droid** [commclassroom/commclassroomBackend#40]
### Is your feature request related to a problem? Please describe.

Deals with the developer guide and the new schema #38

### Describe the solution you'd like

I am working on adding the new schema and the appropriate validations

**Comment by Saatvik-droid** [comment]
I'll link a PR once my initial PR is merged

**Comment by Vyvy-vi** [comment]
@Saatvik-droid I think there's already a PR open for this - #42

**Comment by Saatvik-droid** [comment]
I have already coded it all out just wanted to be assigned at the time of opening this issue, I have no way of knowing someone was working on it 
I'll just rebase my local copy I guess

**Comment by Vyvy-vi** [comment]
the issue is still needed 😅
