### ISSUE TITLE
can anybody guide how to setup this on local environment

### ISSUE THREAD

**Issue by R11manish** [commclassroom/commclassroomBackend#41]
i am getting `connect ECONNREFUSED 127.0.0.1:27017` . or can anybody guide me what kind of schema i have to setup.

**Comment by divyanshu-parihar** [comment]
@R11manish
you need to start mongod (mongo demon) in background , so database connection can be established. 
[Mongodb Installation Guide](https://stackoverflow.com/questions/20796714/how-do-i-start-mongo-db-from-windows)
