### ISSUE TITLE
Testing Setup

### ISSUE THREAD

**Issue by YashKumarVerma** [commclassroom/commclassroomBackend#5]
setup a testing framework and write a sample test that just passes to ensure that the framework is setup properly.

**Comment by mahendra1290** [comment]
@YashKumarVerma I think we can use jest for testing.

**Comment by divyanshu-parihar** [comment]
@mahendra1290 I have opened a pr for adding jest lib with some sample tests here #22

**Comment by mahendra1290** [comment]
@divyanshu-parihar cool

**Comment by divyanshu-parihar** [comment]
I think this issue shoud be closed now.
