### ISSUE TITLE
Setup issue and PR templates

### ISSUE THREAD

**Issue by YashKumarVerma** [commclassroom/commclassroomBackend#7]
Issue templates
- BUG REPORT
- FEATURE REQUEST

Pull Request templates should have
- issue being resolved
- what's done in this pr
- testing required, if, then
- screenshots if applicable
- logs

**Comment by Saatvik-droid** [comment]
You need settings permissions for this, for anyone trying to take this on.

**Comment by YashKumarVerma** [comment]
> You need settings permissions for this, for anyone trying to take this on.

placing the files in the `.github` directory is needed for them to work.  This issue can be closed by adding those.

**Comment by ShaileshKumar007** [comment]
Hi @YashKumarVerma . I want to work on this issue. But plz tell me where to add issue and PR templates as there is no  .github directory in the project?

**Comment by YashKumarVerma** [comment]
Create a directory then

**Comment by ShaileshKumar007** [comment]
Got it. 
If no one is working on this issue then plz let me work on this.
