### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by YashKumarVerma** [commclassroom/commclassroomBackend#8]
add a docker file that enables containerization

**Comment by divyanshu-parihar** [comment]
I am planning to take this issue. If anyone want to contribute , please tell me

**Comment by divyanshu-parihar** [comment]
can you give me some setup guide  on how to set this project locally . 
As  there is not contribution guide till now  and   I don't have much experience with "config" package. I have having some problems with that

**Comment by Sahil-kachhap** [comment]
If this issue is still open. Then, can I work on this issue.
